[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
DiffEqPhysics = "055956cb-9e8b-5191-98cc-73ae4a59e68a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
ModelingToolkitStandardLibrary = "16a59e39-deab-5bd0-87e4-056b12336739"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SciMLWorkshop = "6821e370-b0bb-497c-beb7-809790cbeb12"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
AlgebraicMultigrid = "0.5"
BenchmarkTools = "1"
ControlSystemsBase = "1"
DiffEqDevTools = "2"
DiffEqOperators = "4"
DiffEqPhysics = "3"
DifferentialEquations = "7.6"
Documenter = "0.27, 1"
GlobalSensitivity = "2"
JumpProcesses = "9"
ModelingToolkit = "8"
ModelingToolkitStandardLibrary = "1"
Plots = "1"
SciMLWorkshop = "0.1"
SparseDiffTools = "1, 2"
Sundials = "4.11.3"
Symbolics = "4,5"
